<?php
// =============================================
// backup-db.php — Auto Database Backup (Pure PHP/PDO)
// ใช้ mysqldump ไม่ได้ (shell_exec ถูก disable) → ใช้ PDO export แทน
//
// เรียกจาก webhook.php ก่อน migrate อัตโนมัติ
// หรือเรียกมือ: https://sdak.obec.in/backup-db.php?key=YOUR_WEBHOOK_SECRET
// =============================================

require_once __DIR__ . '/config/config.php';

// ============ PDO Connection (ไม่ใช้ Medoo เพื่อความเสถียร) ============
function getBackupPDO() {
    static $pdo = null;
    if ($pdo === null) {
        $dsn = DB_TYPE . ':host=' . DB_HOST . ';port=' . DB_PORT . ';dbname=' . DB_NAME . ';charset=' . DB_CHARSET;
        $pdo = new PDO($dsn, DB_USER, DB_PASS, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        ]);
    }
    return $pdo;
}

// ============ ป้องกันเรียกจากภายนอก ============
$allowedKey = defined('WEBHOOK_SECRET') ? WEBHOOK_SECRET : '';
$isWebhook = (php_sapi_name() !== 'cli' && !isset($_GET['key']));
$isCLI = (php_sapi_name() === 'cli');
$validKey = !empty($allowedKey) && ($_GET['key'] ?? '') === $allowedKey;

if (!$isWebhook && !$isCLI && !$validKey) {
    http_response_code(403);
    die('Forbidden — ต้องใส่ ?key=xxx');
}

// ============ CONFIG ============
$backupDir = __DIR__ . '/backups/db';
$maxBackups = 10; // เก็บไว้ไม่เกิน 10 ไฟล์ ลบเก่าสุดอัตโนมัติ
// ================================

$result = ['status' => 'ok', 'file' => '', 'tables' => 0, 'size' => 0, 'error' => ''];

try {
    // สร้างโฟลเดอร์
    if (!is_dir($backupDir)) {
        @mkdir($backupDir, 0755, true);
        // สร้าง .htaccess ป้องกันเข้าถึงจากเว็บ
        @file_put_contents($backupDir . '/.htaccess', "Deny from all\n");
    }

    $pdo = getBackupPDO();
    $dbName = DB_NAME;
    $timestamp = date('Y-m-d_His');
    $filename = "backup_{$dbName}_{$timestamp}.sql";
    $filepath = $backupDir . '/' . $filename;

    $sql = '';
    $tableCount = 0;

    // Header
    $sql .= "-- =============================================\n";
    $sql .= "-- Database Backup: {$dbName}\n";
    $sql .= "-- Date: " . date('Y-m-d H:i:s') . "\n";
    $sql .= "-- Auto-generated by backup-db.php\n";
    $sql .= "-- =============================================\n\n";
    $sql .= "SET FOREIGN_KEY_CHECKS = 0;\n\n";

    // ดึงรายชื่อตารางทั้งหมด
    $tables = $pdo->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);

    foreach ($tables as $table) {
        $tableCount++;

        // DROP + CREATE TABLE
        $sql .= "-- -------------------------------------------------\n";
        $sql .= "-- Table: {$table}\n";
        $sql .= "-- -------------------------------------------------\n";
        $sql .= "DROP TABLE IF EXISTS `{$table}`;\n";

        $createStmt = $pdo->query("SHOW CREATE TABLE `{$table}`")->fetch();
        $sql .= $createStmt['Create Table'] . ";\n\n";

        // INSERT data
        $rows = $pdo->query("SELECT * FROM `{$table}`")->fetchAll(PDO::FETCH_ASSOC);

        if (count($rows) > 0) {
            $columns = array_keys($rows[0]);
            $colList = '`' . implode('`, `', $columns) . '`';

            // แบ่ง INSERT เป็น batch ละ 100 rows
            $chunks = array_chunk($rows, 100);
            foreach ($chunks as $chunk) {
                $values = [];
                foreach ($chunk as $row) {
                    $vals = [];
                    foreach ($row as $val) {
                        if ($val === null) {
                            $vals[] = 'NULL';
                        } else {
                            $vals[] = $pdo->quote($val);
                        }
                    }
                    $values[] = '(' . implode(', ', $vals) . ')';
                }
                $sql .= "INSERT INTO `{$table}` ({$colList}) VALUES\n";
                $sql .= implode(",\n", $values) . ";\n";
            }
            $sql .= "\n";
        }
    }

    $sql .= "SET FOREIGN_KEY_CHECKS = 1;\n";
    $sql .= "\n-- Backup complete: {$tableCount} tables\n";

    // เขียนไฟล์
    file_put_contents($filepath, $sql);
    $filesize = filesize($filepath);

    $result['file'] = $filename;
    $result['tables'] = $tableCount;
    $result['size'] = $filesize;

    // ลบ backup เก่าถ้าเกิน $maxBackups
    $backupFiles = glob($backupDir . '/backup_*.sql');
    if (count($backupFiles) > $maxBackups) {
        usort($backupFiles, function($a, $b) { return filemtime($a) - filemtime($b); });
        $toDelete = count($backupFiles) - $maxBackups;
        for ($i = 0; $i < $toDelete; $i++) {
            @unlink($backupFiles[$i]);
        }
    }

} catch (\Throwable $e) {
    $result['status'] = 'error';
    $result['error'] = $e->getMessage();
}

// ถ้าเรียกจาก webhook → return ผลลัพธ์
if ($isWebhook) {
    return $result;
}

// ถ้าเรียกจาก browser/CLI → แสดงผล
header('Content-Type: text/plain; charset=utf-8');
if ($result['status'] === 'ok') {
    echo "✅ Backup OK\n";
    echo "File: {$result['file']}\n";
    echo "Tables: {$result['tables']}\n";
    echo "Size: " . number_format($result['size']) . " bytes\n";
} else {
    echo "❌ Backup FAILED\n";
    echo "Error: {$result['error']}\n";
}
