ALTER TABLE users
ADD COLUMN national_id VARCHAR(20) DEFAULT NULL AFTER bio,
ADD COLUMN first_name VARCHAR(100) DEFAULT NULL AFTER national_id,
ADD COLUMN last_name VARCHAR(100) DEFAULT NULL AFTER first_name,
ADD COLUMN birth_date DATE DEFAULT NULL AFTER last_name,
ADD COLUMN home_address JSON DEFAULT NULL AFTER birth_date,
ADD COLUMN work_address JSON DEFAULT NULL AFTER home_address,
ADD COLUMN education_area VARCHAR(100) DEFAULT NULL AFTER work_address,
ADD COLUMN region VARCHAR(50) DEFAULT NULL AFTER education_area,
ADD COLUMN work_phone VARCHAR(20) DEFAULT NULL AFTER region;
